apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/coordt/demo-app-gitops.git
        revision: HEAD
        directories:
          - path: chart
        values:
          service-type: LoadBalancer
    - pullRequest:
        github:
          owner: coordt
          repo: demo-app-gitops
  template:
    metadata:
      name: 'demo-app-{{ dig "branch" "prod" . }}'
    spec:
      source:
        repoURL: 'https://github.com/coordt/demo-app-gitops.git'
        targetRevision: '{{ dig "branch" "HEAD" . }}'
        path: "chart/" # Path to helm chart
        helm:
          releaseName: 'demo-app-{{ dig "branch" "prod" . }}'
          valuesObject:
            branch: '{{ dig "branch" "master" . }}'
            service:
              type: ClusterIP

      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'demo-app-previews'

      syncPolicy:
        # Automate drift correction
        automated:
          prune: true
          selfHeal: true
        # Create namespace if it does not exist
        syncOptions:
        - CreateNamespace=true
